### ISSUE TITLE
Determine format of output file for tensor or a sequence of tensors

### ISSUE THREAD

**Issue by dowobeha** [neural-polysynthetic-language-modelling/iiksiin#3]

**Comment by dowobeha** [comment]
Obvious options include:

1. Binary file
2. XML file
3. Other (non-XML) text file

@ftyers, what do you think? At the moment I'm inclined to start with an XML file.

**Comment by ftyers** [comment]
I think either text (TSV style) or XML would work fine. I wouldn't go with binary to start with (although it should be an option at some point).

**Comment by dowobeha** [comment]
For now we will be using the Python pickle format.
